name: Release Build

on:
  workflow_dispatch: # Запуск вручную из UI GitHub
  # push:
  #   tags: ['v*']
  # push:
  #   branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Generate automatic version
      id: version
      run: |
        # Получаем базовую версию из csproj
        $baseVersion = (Select-String -Path "Dedupligator.App/Dedupligator.App.csproj" -Pattern '<Version>([^<]+)</Version>').Matches.Groups[1].Value
        
        # Генерируем уникальный билд-идентификатор
        $commitShort = "$(git rev-parse --short HEAD)"
        $buildTimestamp = Get-Date -Format "yyyyMMddHHmm"
        $buildVersion = "$baseVersion.$buildTimestamp-$commitShort"
        
        echo "BASE_VERSION=$baseVersion" >> $env:GITHUB_ENV
        echo "BUILD_VERSION=$buildVersion" >> $env:GITHUB_ENV
        echo "BUILD_TIMESTAMP=$buildTimestamp" >> $env:GITHUB_ENV
        echo "COMMIT_SHORT=$commitShort" >> $env:GITHUB_ENV
        
        echo "Base Version: $baseVersion"
        echo "Build Version: $buildVersion"
        echo "Build Timestamp: $buildTimestamp"
        echo "Commit Short: $commitShort"
        
    - name: Build solution with auto version
      run: |
        # Собираем все проекты с автоматической версией
        dotnet build -c Release `
          /p:Version=$env:BASE_VERSION `
          /p:AssemblyVersion=$env:BASE_VERSION.0 `
          /p:FileVersion=$env:BASE_VERSION.0 `
          /p:InformationalVersion=$env:BUILD_VERSION

    - name: Publish application
      run: |
        dotnet publish Dedupligator.App/Dedupligator.App.csproj `
          -c Release `
          -r win-x64 `
          --self-contained `
          -o publish_output `
          /p:Version=$env:BASE_VERSION `
          /p:AssemblyVersion=$env:BASE_VERSION.0 `
          /p:FileVersion=$env:BASE_VERSION.0 `
          /p:InformationalVersion=$env:BUILD_VERSION
        
    #- name: Download and install Inno Setup
      # run: |
      #   Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "InnoSetup.exe"
      #   Start-Process -FilePath "InnoSetup.exe" -ArgumentList "/SILENT /NORESTART" -Wait
        
    - name: Create setup script
      run: |
        $setupScript = @"
        [Setup]
        AppName=Dedupligator
        AppVersion=$env:BASE_VERSION
        AppVerName=Dedupligator $env:BUILD_VERSION
        AppPublisher=Dmitriy Suvorov
        AppPublisherURL=https://github.com/dimka59ru/dedupligator
        AppSupportURL=https://github.com/dimka59ru/dedupligator/issues
        AppUpdatesURL=https://github.com/dimka59ru/dedupligator/releases
        DefaultDirName={autopf}\Dedupligator
        DefaultGroupName=Dedupligator
        OutputDir=output
        OutputBaseFilename=Dedupligator-Setup-$env:BUILD_VERSION
        Compression=lzma2
        SolidCompression=yes
        ArchitecturesAllowed=x64
        ArchitecturesInstallIn64BitMode=x64
        VersionInfoVersion=$env:BASE_VERSION.0
        VersionInfoTextVersion=$env:BUILD_VERSION
        
        [Languages]
        Name: "english"; MessagesFile: "compiler:Default.isl"
        
        [Files]
        Source: "publish_output\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
        
        [Icons]
        Name: "{group}\Dedupligator"; Filename: "{app}\Dedupligator.exe"
        Name: "{autodesktop}\Dedupligator"; Filename: "{app}\Dedupligator.exe"
        
        [Run]
        Filename: "{app}\Dedupligator.exe"; Description: "Launch Application"; Flags: nowait postinstall skipifsilent
        "@
        
        $setupScript | Out-File -Encoding ASCII setup.iss
        
    - name: Build installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: src/setup.iss
        options: /O+
      
    - name: Create Git Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v$env:BUILD_VERSION" -m "Auto-generated build $env:BUILD_VERSION"
        git push origin "v$env:BUILD_VERSION"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v$env:BUILD_VERSION"
        name: "Dedupligator $env:BUILD_VERSION"
        body: |
          ## Automatic Build
          
          **Version**: $env:BUILD_VERSION
          **Base Version**: $env:BASE_VERSION
          **Build Date**: $env:BUILD_TIMESTAMP
          **Commit**: [$env:COMMIT_SHORT](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          
          ### Changes
          This is an automated build from the main branch.
          
          [Download installer](Dedupligator-Setup-$env:BUILD_VERSION.exe)
        files: output/*.exe