name: Release Build

on:
  workflow_dispatch: # Запуск вручную из UI GitHub
  # push:
  #   tags: ['v*']
  # push:
  #   branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Download runtime dependencies
      run: |
        # Создаем папку для зависимостей
        New-Item -ItemType Directory -Path "dependencies" -Force
        
        # Скачиваем .NET Desktop Runtime
        Invoke-WebRequest -Uri "https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer" -OutFile "dependencies/dotnet-runtime.exe"
        
        # Скачиваем Visual C++ Redistributable
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "dependencies/vcredist_x64.exe"
        
    - name: Generate automatic version
      id: version
      run: |
        # Получаем базовую версию из csproj
        $baseVersion = (Select-String -Path "Dedupligator.App/Dedupligator.App.csproj" -Pattern '<Version>([^<]+)</Version>').Matches.Groups[1].Value
        
        # Генерируем уникальный билд-идентификатор
        $commitShort = "$(git rev-parse --short HEAD)"
        $buildTimestamp = Get-Date -Format "yyyyMMddHHmm"
        $buildVersion = "$baseVersion.$buildTimestamp-$commitShort"
        
        echo "BASE_VERSION=$baseVersion" >> $env:GITHUB_ENV
        echo "BUILD_VERSION=$buildVersion" >> $env:GITHUB_ENV
        echo "BUILD_TIMESTAMP=$buildTimestamp" >> $env:GITHUB_ENV
        echo "COMMIT_SHORT=$commitShort" >> $env:GITHUB_ENV
        
        echo "Base Version: $baseVersion"
        echo "Build Version: $buildVersion"
        echo "Build Timestamp: $buildTimestamp"
        echo "Commit Short: $commitShort"
        
    - name: Build solution with auto version
      run: |
        # Собираем все проекты с автоматической версией
        dotnet build -c Release `
          /p:Version=$env:BASE_VERSION `
          /p:AssemblyVersion=$env:BASE_VERSION.0 `
          /p:FileVersion=$env:BASE_VERSION.0 `
          /p:InformationalVersion=$env:BUILD_VERSION

    - name: Publish application
      run: |
        dotnet publish Dedupligator.App/Dedupligator.App.csproj `
          -c Release `
          -r win-x64 `
          --self-contained `
          -o publish_output `
          /p:ApplicationIcon=../Dedupligator.App/Assets/logo.ico `
          /p:Version=$env:BASE_VERSION `
          /p:AssemblyVersion=$env:BASE_VERSION.0 `
          /p:FileVersion=$env:BASE_VERSION.0 `
          /p:InformationalVersion=$env:BUILD_VERSION

        # Копируем зависимости в выходную папку
        Copy-Item -Path "dependencies/*" -Destination "publish_output/" -Force
        
    - name: Create setup script
      run: |
        $setupScript = @"
        [Setup]
        AppName=Dedupligator
        AppVersion=$env:BASE_VERSION
        AppVerName=Dedupligator $env:BUILD_VERSION
        AppPublisher=Dmitriy Suvorov
        AppPublisherURL=https://github.com/dimka59ru/dedupligator
        AppSupportURL=https://github.com/dimka59ru/dedupligator/issues
        AppUpdatesURL=https://github.com/dimka59ru/dedupligator/releases
        DefaultDirName={autopf}\Dedupligator
        DefaultGroupName=Dedupligator
        OutputDir=output
        OutputBaseFilename=Dedupligator-Setup-$env:BUILD_VERSION
        Compression=lzma2
        SolidCompression=yes
        ArchitecturesAllowed=x64
        ArchitecturesInstallIn64BitMode=x64
        VersionInfoVersion=$env:BASE_VERSION.0
        VersionInfoTextVersion=$env:BUILD_VERSION
        SetupIconFile=publish_output\Assets\logo.ico
        
        [Languages]
        Name: "english"; MessagesFile: "compiler:Default.isl"
        
        [Files]
        Source: "publish_output\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
        ; Копируем иконку отдельно для ярлыков
        Source: "publish_output\Assets\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
        
        [Icons]
        Name: "{group}\Dedupligator"; Filename: "{app}\Dedupligator.exe"; IconFilename: "{app}\logo.ico"
        Name: "{autodesktop}\Dedupligator"; Filename: "{app}\Dedupligator.exe"
        Name: "{group}\{cm:UninstallProgram,Dedupligator}"; Filename: "{uninstallexe}"
        
        [Run]
        ; Устанавливаем зависимости перед запуском приложения
        Filename: "{app}\dotnet-runtime.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing .NET Runtime..."; Flags: waituntilterminated
        Filename: "{app}\vcredist_x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing Visual C++ Redistributable..."; Flags: waituntilterminated
        Filename: "{app}\Dedupligator.exe"; Description: "Launch Application"; Flags: nowait postinstall skipifsilent

        [UninstallDelete]
        Type: filesandordirs; Name: "{localappdata}\Dedupligator"

        [Code]
        function IsDotNetDetected(version: string; service: cardinal): boolean;
        // Проверка наличия .NET Framework
        var
            key: string;
            install, release: cardinal;
            success: boolean;
        begin
            key := 'SOFTWARE\Microsoft\NET Framework Setup\NDP\' + version;
            if version = 'net8.0' then
                key := 'SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost\';
        
            success := RegQueryDWordValue(HKLM, key, 'Version', install);
            Result := success and (install >= service);
        end;
    
        function InitializeSetup(): Boolean;
        begin
          // Проверяем, установлен ли .NET Runtime
          if not IsDotNetDetected('net8.0', 0) then
          begin
            MsgBox('Dedupligator requires .NET 8.0 Desktop Runtime. It will be installed now.', mbInformation, MB_OK);
          end;
          Result := True;
        end;
        "@
        
        $setupScript | Out-File -Encoding ASCII setup.iss
        
    - name: Build installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: setup.iss
        options: /O+
      
    - name: Create Git Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v$env:BUILD_VERSION" -m "Auto-generated build $env:BUILD_VERSION"
        git push origin "v$env:BUILD_VERSION"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.BUILD_VERSION }}"
        name: "Dedupligator ${{ env.BUILD_VERSION }}"
        body: |
          ## Automatic Build
      
          **Version**: ${{ env.BUILD_VERSION }}
          **Base Version**: ${{ env.BASE_VERSION }}
          **Build Date**: ${{ env.BUILD_TIMESTAMP }}
          **Commit**: [${{ env.COMMIT_SHORT }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
      
          [Download Installer](https://github.com/${{ github.repository }}/releases/download/v${{ env.BUILD_VERSION }}/Dedupligator-Setup-${{ env.BUILD_VERSION }}.exe)
      
          ### System Requirements
          - Windows 10/11 x64
          - .NET 8.0 Desktop Runtime (will be installed automatically)
          - Visual C++ Redistributable (will be installed automatically)

          ### Installation
          1. Download the installer above
          2. Run the executable
          3. Follow the setup wizard
      
          ### Changes
          This is an automated build from the main branch.
        files: output/*.exe